theme = "my_catppuccin_mocha"

[editor]
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "⤶"

[editor.indent-guides]
render = true
character = "▎"

[keys.normal]
"~"     = "switch_to_uppercase"
"A-`"   = "switch_case"
# waiting on https://github.com/helix-editor/helix/pull/4939
# "C-(" = "rotate_selection_contents_backward"
# "C-)" = "rotate_selection_contents_forward"

[keys.normal.space]
w = ":write"
q = ":quit"

[keys.select]
"~"     = "switch_to_uppercase"
"A-`"   = "switch_case"
# "C-(" = "rotate_selection_contents_backward"
# "C-)" = "rotate_selection_contents_forward"

[keys.select.space]
w = ":write"
q = ":quit"
